server:
  port: 8082
spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5433/stripe_platform?currentSchema=wallet
    username: wallet_svc
    password: wallet_dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: wallet
  flyway:
    schemas: wallet
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: all
      properties:
        enable.idempotence: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
